### PR TITLE
Fix for Quests that need items to be clicked  Better .Info on game objects

### PR DESCRIPTION
**Pull request by nalgol**
Fix for Quests that need items to be clicked 
2 things need to be done in sql 
1. update the objcetid in questsobjectivs to match the clickable item
like
UPDATE `test`.`quests_objectives` SET `ObjID`='561' WHERE `Guid`='2783';  // its 
2. to make the item clickable its kind of a hack
change Unks from 7680 0 14080 1312 706 563 to 7680 1 18079 1316 1228 19835
like
UPDATE `test`.`gameobject_protos` SET `Unks`='7680 1 18079 1316 1228 19835' WHERE `Entry`='561';

the example is form the destro quest Pillaging first quest hub

### CODE REVIEW

**Comment by nalgol** [comment]
http://youtu.be/edPFurEBcqk

**Comment by MaxHayman** [comment]
The object spawn info will be good :) However the quest object thing seems confusing, i'm gonna have a read through it some time. To see if we don't have to modify any of the quest db info. Or does this fix all the object quests?

**Comment by nalgol** [comment]
the c# code fixes all quests of that typ however we need to check all questconditions sice all object_ids never match with  the gameobject_protos entry (id) its no biggy though with my tool

**Comment by MaxHayman** [comment]
Implemented the .info for GameObjects in 4e4629cce05b05a8dd8310542331b2afd4208186. Sorry it took soooo long!

**Pull request closed without merging**
