### PR TITLE
Waypoints fix and cleanup

### PR DESCRIPTION
**Pull request by bozzax**
Add, delete, save Waypoints to database and random moving spawns

### CODE REVIEW

**Comment by tony898** [comment]
hey bozzax do you have a contact place ? good fix

**Comment by bozzax** [comment]
Added mail to profile and thx

**Comment by tony898** [comment]
ok i sent you a pm

**Comment by tony898** [comment]
can you fix other things on this please looking forward to your next update fixs

**Comment by tony898** [comment]
nice. theres an error when teleporting to a zone .it teleports to  zone o  an empty zone untill you teleport again can u fix this error

**Pull request closed without merging**
